valor = float(input('Ingrese el valor que le establece a su hora de trabajo: '))
sem = float(valor) * float(40)
men = float(valor) * float(160)
print("Usted como Freelancer puede cobrar semanalmente por su trabajo: " + str(sem))
print("Usted como Freelancer puede cobrar mensualmente por su trabajo: " + str(men))
